name: cfipv404  # Example of a different name

on:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 selenium webdriver-manager

    - name: Run Python script
      run: |
        python ipv404.py

    - name: Configure Git
      run: |
        git config --global user.name "yuanxiawan"
        git config --global user.email "yuanxiawan@gmail.com"

    - name: Commit and push generated files
      run: |
        git add cloudflare_ipv402.txt
        git commit -m "Auto-update Cloudflare IPv4 addresses" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
